// Insights listing (blog.html): topic filters, title search, hero stats and
// scroll-reveal animation. The cards themselves are static HTML generated by
// scripts/blog-build.js, so the page is fully readable without JavaScript.
(function () {
  var grid = document.querySelector('.blog-listing-grid');
  var filters = document.querySelector('.category-filters');
  if (!grid) return;
  var cards = [].slice.call(grid.querySelectorAll('.blog-listing-card'));
  var reduce = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  /* ---------- hero stats */
  var hero = document.querySelector('.page-hero .container');
  if (hero) {
    var topics = {};
    cards.forEach(function (c) { topics[c.getAttribute('data-cat')] = true; });
    var latest = cards[0] && cards[0].querySelector('.blog-date');
    var stats = document.createElement('ul');
    stats.className = 'blc-stats';
    stats.innerHTML =
      '<li><strong data-count="' + cards.length + '">0</strong><span>articles</span></li>' +
      '<li><strong data-count="' + Object.keys(topics).length + '">0</strong><span>topics</span></li>' +
      (latest ? '<li><strong>' + latest.textContent + '</strong><span>latest update</span></li>' : '');
    hero.appendChild(stats);
    [].forEach.call(stats.querySelectorAll('[data-count]'), function (el) {
      var to = +el.getAttribute('data-count');
      if (reduce) { el.textContent = to; return; }
      var t0 = null, done = false;
      function step(ts) {
        if (done) return;
        if (!t0) t0 = ts;
        var p = Math.min(1, (ts - t0) / 900);
        el.textContent = Math.round(to * (1 - Math.pow(1 - p, 3)));
        if (p < 1) requestAnimationFrame(step); else done = true;
      }
      requestAnimationFrame(step);
      // Background tabs pause animation frames; land on the final value regardless.
      setTimeout(function () { done = true; el.textContent = to; }, 1100);
    });
  }

  /* ---------- toolbar: search beside the topic filters */
  var state = { cat: 'all', q: '' };
  var status = document.createElement('p');
  status.className = 'blc-status';
  status.setAttribute('aria-live', 'polite');
  var empty = document.createElement('div');
  empty.className = 'blc-empty';
  empty.hidden = true;
  empty.innerHTML = '<p>No article matches that search.</p><button type="button" class="btn btn-secondary">Show all articles</button>';
  grid.parentNode.insertBefore(empty, grid.nextSibling);

  if (filters) {
    var bar = document.createElement('div');
    bar.className = 'blc-toolbar';
    filters.parentNode.insertBefore(bar, filters);
    bar.appendChild(filters);
    var search = document.createElement('label');
    search.className = 'blc-search';
    search.innerHTML = '<svg class="icon-svg" viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/></svg>' +
      '<span class="visually-hidden">Search articles</span><input type="search" placeholder="Search articles" autocomplete="off">';
    bar.appendChild(search);
    bar.parentNode.insertBefore(status, bar.nextSibling);
    var input = search.querySelector('input');
    var timer;
    input.addEventListener('input', function () {
      clearTimeout(timer);
      timer = setTimeout(function () { state.q = input.value.trim().toLowerCase(); apply(true); }, 120);
    });
    filters.addEventListener('click', function (e) {
      var b = e.target.closest('button[data-cat]');
      if (!b) return;
      state.cat = b.getAttribute('data-cat');
      [].forEach.call(filters.querySelectorAll('button[data-cat]'), function (x) {
        var on = x === b;
        x.classList.toggle('active', on);
        x.setAttribute('aria-pressed', on ? 'true' : 'false');
      });
      apply(true);
    });
    empty.querySelector('button').addEventListener('click', function () {
      input.value = ''; state.q = ''; state.cat = 'all';
      [].forEach.call(filters.querySelectorAll('button[data-cat]'), function (x) {
        var on = x.getAttribute('data-cat') === 'all';
        x.classList.toggle('active', on);
        x.setAttribute('aria-pressed', on ? 'true' : 'false');
      });
      apply(true);
    });
  }

  function apply(animate) {
    var shown = 0;
    cards.forEach(function (c) {
      var hay = (c.querySelector('h2').textContent + ' ' + c.querySelector('.blog-excerpt').textContent).toLowerCase();
      var on = (state.cat === 'all' || c.getAttribute('data-cat') === state.cat) &&
        (!state.q || state.q.split(/\s+/).every(function (w) { return hay.indexOf(w) !== -1; }));
      // The featured layout only applies when the full, unfiltered list is shown.
      c.classList.toggle('is-wide', on && c.classList.contains('is-featured') && state.cat === 'all' && !state.q);
      if (on) {
        if (animate && !reduce) {
          c.style.setProperty('--d', (shown * 40) + 'ms');
          c.classList.remove('is-pop'); void c.offsetWidth; c.classList.add('is-pop');
        }
        c.hidden = false; shown++;
      } else {
        c.hidden = true;
      }
    });
    empty.hidden = shown !== 0;
    var filtered = state.cat !== 'all' || state.q;
    status.textContent = filtered ? 'Showing ' + shown + ' of ' + cards.length + ' articles' : '';
  }
  apply(false);

  /* ---------- scroll reveal */
  if (!reduce && 'IntersectionObserver' in window) {
    grid.classList.add('blc-reveal');
    var io = new IntersectionObserver(function (entries) {
      entries.forEach(function (en) {
        if (en.isIntersecting) { en.target.classList.add('is-visible'); io.unobserve(en.target); }
      });
    }, { rootMargin: '0px 0px -8% 0px', threshold: 0.08 });
    cards.forEach(function (c, i) { c.style.setProperty('--r', (i % 3) * 70 + 'ms'); io.observe(c); });
    // Safety net for prerendered or background tabs.
    setTimeout(function () { cards.forEach(function (c) { c.classList.add('is-visible'); }); }, 2500);
  }
})();
